jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Puppeteer
        uses: browser-actions/setup-puppeteer@latest
      - name: Run script
        run: node index.js
        env:
          ATERNOS_USER: ${{ secrets.ATERNOS_USER }}
          ATERNOS_PASS: ${{ secrets.ATERNOS_PASS }}
