name: Tamcpoco-Portal
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Portal
        run: node index.js
        env:
          ATERNOS_USER: ${{ secrets.ATERNOS_USER }}
          ATERNOS_PASS: ${{ secrets.ATERNOS_PASS }}
